# Generated by Django 4.2.7 on 2023-11-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='shops',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='shops',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='shops',
            name='sells',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='shops',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
